# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r

os:
 - linux
 - osx

r:
 - oldrel
 - release
 - devel
 - 3.3.0

r_binary_packages:
 - svUnit
 - XML
r_packages:
 - methods

env:
  - TravisCI=true

cache: packages
warnings_are_errors: true

before_install:
- cd pkg

script:
- R CMD build .
- R CMD check *tar.gz
- Rscript -e 'devtools::install()' --no-init-file
