# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

os:
- linux
- osx

r:
- oldrel
- release
- devel
- 3.3.0

env:
- TravisCI=true

script:
- R CMD build .
- R CMD check *tar.gz
- Rscript -e 'devtools::install()' --no-init-file
