# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r

os:
 - linux
 - osx

r:
 - oldrel
 - release
 - devel
 - 3.3.0

 matrix:
  exclude:
  - os: osx
    r: devel

r_binary_packages:
 - svUnit
 - XML
r_packages:
 - methods

env:
  - TravisCI=true

cache: packages
warnings_are_errors: true

before_install:
- cd pkg
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo chown -R $(whoami) /usr/local/share/man/man7; brew install libgit2; fi

install:
- Rscript -e 'install.packages(c("devtools"));if (!all(c("devtools") %in% installed.packages())) { q(status = 1, save = "no")}' --no-init-file
- Rscript -e 'devtools::install_deps(dep = T)' --no-init-file
- Rscript -e 'devtools::document()'

script:
- R CMD build .
- R CMD check *tar.gz
- Rscript -e 'devtools::install()' --no-init-file
