# Do not edit!  This file was autogenerated
#      by ./cleanup
#      on Fri Mar 26 11:00:14 CET 2010
#
# SVNVERSION as reported by svnversion at that point in time,

SVNVERSION <- "9809"
SVNDATE <- "2010-03-09 09:22:36"

